export const english26ToGeom = {
  id: "3a352376-1d40-4b7f-a3db-38280fc782eb",
  name: "english(26) to geometric symbols",
  inputSet: "english26",
  outputSet: "unicode geomtric",
  map: [
    { in: "A", out: "⬠" },
    { in: "B", out: "◯" },
    { in: "C", out: "⬢" },
    { in: "D", out: "◆" },
    { in: "E", out: "◼" },
    { in: "F", out: "⬣" },
    { in: "G", out: "⬡" },
    { in: "H", out: "⬤" },
    { in: "I", out: "◻" },
    { in: "J", out: "⬟" },
    { in: "K", out: "▣" },
    { in: "L", out: "◪" },
    { in: "M", out: "◵" },
    { in: "N", out: "◖" },
    { in: "O", out: "◶" },
    { in: "P", out: "⬕" },
    { in: "Q", out: "⬖" },
    { in: "R", out: "◓" },
    { in: "S", out: "⬔" },
    { in: "T", out: "◉" },
    { in: "U", out: "⬙" },
    { in: "V", out: "◧" },
    { in: "W", out: "⬭" },
    { in: "X", out: "⬚" },
    { in: "Y", out: "⚬" },
    { in: "Z", out: "⬘" },
  ],
};

export const english26ToCreepy = {
  id: "0596ef97-3ea5-431a-bd1b-0227fb28d046",
  name: "english(26) to gothic/creepy symbols",
  inputSet: "english26",
  outputSet: "unicode creepy",
  map: [
    { in: "A", out: "☠" },
    { in: "B", out: "⚰" },
    { in: "C", out: "⚱" },
    { in: "D", out: "☾" },
    { in: "E", out: "✞" },
    { in: "F", out: "✟" },
    { in: "G", out: "☽" },
    { in: "H", out: "⚰" },
    { in: "I", out: "☥" },
    { in: "J", out: "⛧" },
    { in: "K", out: "⛥" },
    { in: "L", out: "⚛" },
    { in: "M", out: "☿" },
    { in: "N", out: "☉" },
    { in: "O", out: "⛓" },
    { in: "P", out: "☍" },
    { in: "Q", out: "♆" },
    { in: "R", out: "⚚" },
    { in: "S", out: "✠" },
    { in: "T", out: "✡" },
    { in: "U", out: "⚕" },
    { in: "V", out: "☭" },
    { in: "W", out: "☬" },
    { in: "X", out: "♁" },
    { in: "Y", out: "⚒" },
    { in: "Z", out: "☯" },
  ],
};

export const english26ToLines = {
  id: "5944038f-97bc-42c8-9212-c52990644cb9",
  name: "english(26) to line-like symbols",
  inputSet: "english26",
  outputSet: "unicode lines",
  map: [
    { in: "A", out: "─" },
    { in: "B", out: "━" },
    { in: "C", out: "│" },
    { in: "D", out: "┃" },
    { in: "E", out: "┄" },
    { in: "F", out: "┅" },
    { in: "G", out: "┆" },
    { in: "H", out: "┇" },
    { in: "I", out: "┈" },
    { in: "J", out: "┉" },
    { in: "K", out: "┊" },
    { in: "L", out: "┋" },
    { in: "M", out: "┌" },
    { in: "N", out: "┍" },
    { in: "O", out: "┎" },
    { in: "P", out: "┏" },
    { in: "Q", out: "┐" },
    { in: "R", out: "┑" },
    { in: "S", out: "┒" },
    { in: "T", out: "┓" },
    { in: "U", out: "└" },
    { in: "V", out: "┕" },
    { in: "W", out: "┖" },
    { in: "X", out: "┗" },
    { in: "Y", out: "┘" },
    { in: "Z", out: "┙" },
  ],
};

export const english26ToScratches = {
  id: "0a0ad37b-b26c-4e35-a7dd-0c04c29ca549",
  name: "english(26) to scratchy symbols",
  inputSet: "english26",
  outputSet: "unicode scratchy",
  map: [
    { in: "A", out: "〰" },
    { in: "B", out: "≋" },
    { in: "C", out: "≇" },
    { in: "D", out: "⎯" },
    { in: "E", out: "≋" },
    { in: "F", out: "⎻" },
    { in: "G", out: "≂" },
    { in: "H", out: "≁" },
    { in: "I", out: "." },
    { in: "J", out: ":" },
    { in: "K", out: "≋" },
    { in: "L", out: "╎" },
    { in: "M", out: "╏" },
    { in: "N", out: ">" },
    { in: "O", out: "<" },
    { in: "P", out: "╲" },
    { in: "Q", out: "X" },
    { in: "R", out: "-" },
    { in: "S", out: "=" },
    { in: "T", out: "_" },
    { in: "U", out: "+" },
    { in: "V", out: "⦚" },
    { in: "W", out: "⦙" },
    { in: "X", out: "⧢" },
    { in: "Y", out: "⧣" },
    { in: "Z", out: "≻" },
  ],
};
